[tool.poetry]
name = "jellyfish-server-sdk"
version = "0.1.0"
description = "\"Python server SDK for the Jellyfish media server\""
authors = ["Jellyfish Team <https://github.com/jellyfish-dev>"]
license = "Apache-2.0"
readme = "README.md"
packages = [{ include = "jellyfish" }]

[tool.poetry.dependencies]
python = "^3.8"
websockets = "^11.0.3"
urllib3 = ">=1.25.3,<2"
pydantic = "<2"
aenum = "^3.1.15"
python-dateutil = "^2.8.2"
betterproto = { git = "https://github.com/danielgtaylor/python-betterproto.git", rev = "v.2.0.0b6" }

[tool.poetry.group.dev.dependencies]
pdoc = "^14.1.0"
pylint = "^2.17.6"

[tool.poetry.group.test.dependencies]
pytest = "^7.4.2"
pytest-asyncio = "^0.21.1"

[build-system]
requires = ["poetry-core>=1.6.0"]
build-backend = "poetry.core.masonry.api"
